//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PirateTUO2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myDeckTextBox1 {
            get {
                return ((string)(this["myDeckTextBox1"]));
            }
            set {
                this["myDeckTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myDeckTextBox2 {
            get {
                return ((string)(this["myDeckTextBox2"]));
            }
            set {
                this["myDeckTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myDeckTextBox3 {
            get {
                return ((string)(this["myDeckTextBox3"]));
            }
            set {
                this["myDeckTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string enemyDeckTextBox1 {
            get {
                return ((string)(this["enemyDeckTextBox1"]));
            }
            set {
                this["enemyDeckTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string enemyDeckTextBox2 {
            get {
                return ((string)(this["enemyDeckTextBox2"]));
            }
            set {
                this["enemyDeckTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string enemyDeckTextBox3 {
            get {
                return ((string)(this["enemyDeckTextBox3"]));
            }
            set {
                this["enemyDeckTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myFortComboBox1 {
            get {
                return ((string)(this["myFortComboBox1"]));
            }
            set {
                this["myFortComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myFortComboBox2 {
            get {
                return ((string)(this["myFortComboBox2"]));
            }
            set {
                this["myFortComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myFortComboBox3 {
            get {
                return ((string)(this["myFortComboBox3"]));
            }
            set {
                this["myFortComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string enemyFortComboBox1 {
            get {
                return ((string)(this["enemyFortComboBox1"]));
            }
            set {
                this["enemyFortComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string enemyFortComboBox2 {
            get {
                return ((string)(this["enemyFortComboBox2"]));
            }
            set {
                this["enemyFortComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string enemyFortComboBox3 {
            get {
                return ((string)(this["enemyFortComboBox3"]));
            }
            set {
                this["enemyFortComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string bgeComboBox1 {
            get {
                return ((string)(this["bgeComboBox1"]));
            }
            set {
                this["bgeComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string bgeComboBox2 {
            get {
                return ((string)(this["bgeComboBox2"]));
            }
            set {
                this["bgeComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string bgeComboBox3 {
            get {
                return ((string)(this["bgeComboBox3"]));
            }
            set {
                this["bgeComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string yourBgeComboBox1 {
            get {
                return ((string)(this["yourBgeComboBox1"]));
            }
            set {
                this["yourBgeComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string yourBgeComboBox2 {
            get {
                return ((string)(this["yourBgeComboBox2"]));
            }
            set {
                this["yourBgeComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string yourBgeComboBox3 {
            get {
                return ((string)(this["yourBgeComboBox3"]));
            }
            set {
                this["yourBgeComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string enemyBgeComboBox1 {
            get {
                return ((string)(this["enemyBgeComboBox1"]));
            }
            set {
                this["enemyBgeComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string enemyBgeComboBox2 {
            get {
                return ((string)(this["enemyBgeComboBox2"]));
            }
            set {
                this["enemyBgeComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string enemyBgeComboBox3 {
            get {
                return ((string)(this["enemyBgeComboBox3"]));
            }
            set {
                this["enemyBgeComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Surge - Ordered")]
        public string gameModeComboBox1 {
            get {
                return ((string)(this["gameModeComboBox1"]));
            }
            set {
                this["gameModeComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Surge - Ordered")]
        public string gameModeComboBox2 {
            get {
                return ((string)(this["gameModeComboBox2"]));
            }
            set {
                this["gameModeComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Surge - Ordered")]
        public string gameModeComboBox3 {
            get {
                return ((string)(this["gameModeComboBox3"]));
            }
            set {
                this["gameModeComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("climb")]
        public string gameOperationComboBox1 {
            get {
                return ((string)(this["gameOperationComboBox1"]));
            }
            set {
                this["gameOperationComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("climb")]
        public string gameOperationComboBox2 {
            get {
                return ((string)(this["gameOperationComboBox2"]));
            }
            set {
                this["gameOperationComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("climb")]
        public string gameOperationComboBox3 {
            get {
                return ((string)(this["gameOperationComboBox3"]));
            }
            set {
                this["gameOperationComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameMISTextBox1 {
            get {
                return ((string)(this["gameMISTextBox1"]));
            }
            set {
                this["gameMISTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameMISTextBox2 {
            get {
                return ((string)(this["gameMISTextBox2"]));
            }
            set {
                this["gameMISTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameMISTextBox3 {
            get {
                return ((string)(this["gameMISTextBox3"]));
            }
            set {
                this["gameMISTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameHarmonicMeanCheckBox1 {
            get {
                return ((string)(this["gameHarmonicMeanCheckBox1"]));
            }
            set {
                this["gameHarmonicMeanCheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameHarmonicMeanCheckBox2 {
            get {
                return ((string)(this["gameHarmonicMeanCheckBox2"]));
            }
            set {
                this["gameHarmonicMeanCheckBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameHarmonicMeanCheckBox3 {
            get {
                return ((string)(this["gameHarmonicMeanCheckBox3"]));
            }
            set {
                this["gameHarmonicMeanCheckBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameFundTextBox1 {
            get {
                return ((string)(this["gameFundTextBox1"]));
            }
            set {
                this["gameFundTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameFundTextBox2 {
            get {
                return ((string)(this["gameFundTextBox2"]));
            }
            set {
                this["gameFundTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameFundTextBox3 {
            get {
                return ((string)(this["gameFundTextBox3"]));
            }
            set {
                this["gameFundTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameExtraFlagsTextBox1 {
            get {
                return ((string)(this["gameExtraFlagsTextBox1"]));
            }
            set {
                this["gameExtraFlagsTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameExtraFlagsTextBox2 {
            get {
                return ((string)(this["gameExtraFlagsTextBox2"]));
            }
            set {
                this["gameExtraFlagsTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameExtraFlagsTextBox3 {
            get {
                return ((string)(this["gameExtraFlagsTextBox3"]));
            }
            set {
                this["gameExtraFlagsTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameTUODebugCheckBox1 {
            get {
                return ((string)(this["gameTUODebugCheckBox1"]));
            }
            set {
                this["gameTUODebugCheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameTUODebugCheckBox2 {
            get {
                return ((string)(this["gameTUODebugCheckBox2"]));
            }
            set {
                this["gameTUODebugCheckBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameTUODebugCheckBox3 {
            get {
                return ((string)(this["gameTUODebugCheckBox3"]));
            }
            set {
                this["gameTUODebugCheckBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string gameCPUThreadsTextBox1 {
            get {
                return ((string)(this["gameCPUThreadsTextBox1"]));
            }
            set {
                this["gameCPUThreadsTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string gameCPUThreadsTextBox2 {
            get {
                return ((string)(this["gameCPUThreadsTextBox2"]));
            }
            set {
                this["gameCPUThreadsTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string gameCPUThreadsTextBox3 {
            get {
                return ((string)(this["gameCPUThreadsTextBox3"]));
            }
            set {
                this["gameCPUThreadsTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameCPUx86CheckBox1 {
            get {
                return ((string)(this["gameCPUx86CheckBox1"]));
            }
            set {
                this["gameCPUx86CheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameCPUx86CheckBox2 {
            get {
                return ((string)(this["gameCPUx86CheckBox2"]));
            }
            set {
                this["gameCPUx86CheckBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameCPUx86CheckBox3 {
            get {
                return ((string)(this["gameCPUx86CheckBox3"]));
            }
            set {
                this["gameCPUx86CheckBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryListBox1 {
            get {
                return ((string)(this["inventoryListBox1"]));
            }
            set {
                this["inventoryListBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryListBox2 {
            get {
                return ((string)(this["inventoryListBox2"]));
            }
            set {
                this["inventoryListBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryListBox3 {
            get {
                return ((string)(this["inventoryListBox3"]));
            }
            set {
                this["inventoryListBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryCardAddonsListBox1 {
            get {
                return ((string)(this["inventoryCardAddonsListBox1"]));
            }
            set {
                this["inventoryCardAddonsListBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryCardAddonsListBox2 {
            get {
                return ((string)(this["inventoryCardAddonsListBox2"]));
            }
            set {
                this["inventoryCardAddonsListBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryCardAddonsListBox3 {
            get {
                return ((string)(this["inventoryCardAddonsListBox3"]));
            }
            set {
                this["inventoryCardAddonsListBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventorySeedComboBox1 {
            get {
                return ((string)(this["inventorySeedComboBox1"]));
            }
            set {
                this["inventorySeedComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventorySeedComboBox2 {
            get {
                return ((string)(this["inventorySeedComboBox2"]));
            }
            set {
                this["inventorySeedComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventorySeedComboBox3 {
            get {
                return ((string)(this["inventorySeedComboBox3"]));
            }
            set {
                this["inventorySeedComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bestEffortSeedComboBox1 {
            get {
                return ((string)(this["bestEffortSeedComboBox1"]));
            }
            set {
                this["bestEffortSeedComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bestEffortSeedComboBox2 {
            get {
                return ((string)(this["bestEffortSeedComboBox2"]));
            }
            set {
                this["bestEffortSeedComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bestEffortSeedComboBox3 {
            get {
                return ((string)(this["bestEffortSeedComboBox3"]));
            }
            set {
                this["bestEffortSeedComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gauntletCustomDecksComboBox1 {
            get {
                return ((string)(this["gauntletCustomDecksComboBox1"]));
            }
            set {
                this["gauntletCustomDecksComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gauntletCustomDecksComboBox2 {
            get {
                return ((string)(this["gauntletCustomDecksComboBox2"]));
            }
            set {
                this["gauntletCustomDecksComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gauntletCustomDecksComboBox3 {
            get {
                return ((string)(this["gauntletCustomDecksComboBox3"]));
            }
            set {
                this["gauntletCustomDecksComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gauntletListBox1 {
            get {
                return ((string)(this["gauntletListBox1"]));
            }
            set {
                this["gauntletListBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gauntletListBox2 {
            get {
                return ((string)(this["gauntletListBox2"]));
            }
            set {
                this["gauntletListBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gauntletListBox3 {
            get {
                return ((string)(this["gauntletListBox3"]));
            }
            set {
                this["gauntletListBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDeckLimitLowTextBox1 {
            get {
                return ((string)(this["gameDeckLimitLowTextBox1"]));
            }
            set {
                this["gameDeckLimitLowTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDeckLimitLowTextBox2 {
            get {
                return ((string)(this["gameDeckLimitLowTextBox2"]));
            }
            set {
                this["gameDeckLimitLowTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDeckLimitLowTextBox3 {
            get {
                return ((string)(this["gameDeckLimitLowTextBox3"]));
            }
            set {
                this["gameDeckLimitLowTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDeckLimitHighTextBox1 {
            get {
                return ((string)(this["gameDeckLimitHighTextBox1"]));
            }
            set {
                this["gameDeckLimitHighTextBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDeckLimitHighTextBox2 {
            get {
                return ((string)(this["gameDeckLimitHighTextBox2"]));
            }
            set {
                this["gameDeckLimitHighTextBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDeckLimitHighTextBox3 {
            get {
                return ((string)(this["gameDeckLimitHighTextBox3"]));
            }
            set {
                this["gameDeckLimitHighTextBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameOutputCheckBox1 {
            get {
                return ((string)(this["gameOutputCheckBox1"]));
            }
            set {
                this["gameOutputCheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameOutputCheckBox2 {
            get {
                return ((string)(this["gameOutputCheckBox2"]));
            }
            set {
                this["gameOutputCheckBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameOutputCheckBox3 {
            get {
                return ((string)(this["gameOutputCheckBox3"]));
            }
            set {
                this["gameOutputCheckBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string gameTimeoutTextBox {
            get {
                return ((string)(this["gameTimeoutTextBox"]));
            }
            set {
                this["gameTimeoutTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string gameIterationsComboBox1 {
            get {
                return ((string)(this["gameIterationsComboBox1"]));
            }
            set {
                this["gameIterationsComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string gameIterationsComboBox2 {
            get {
                return ((string)(this["gameIterationsComboBox2"]));
            }
            set {
                this["gameIterationsComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string gameIterationsComboBox3 {
            get {
                return ((string)(this["gameIterationsComboBox3"]));
            }
            set {
                this["gameIterationsComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimGuildComboBox {
            get {
                return ((string)(this["batchSimGuildComboBox"]));
            }
            set {
                this["batchSimGuildComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimMyFortComboBox {
            get {
                return ((string)(this["batchSimMyFortComboBox"]));
            }
            set {
                this["batchSimMyFortComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimEnemyFortComboBox {
            get {
                return ((string)(this["batchSimEnemyFortComboBox"]));
            }
            set {
                this["batchSimEnemyFortComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimBgeComboBox {
            get {
                return ((string)(this["batchSimBgeComboBox"]));
            }
            set {
                this["batchSimBgeComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimYourBgeComboBox {
            get {
                return ((string)(this["batchSimYourBgeComboBox"]));
            }
            set {
                this["batchSimYourBgeComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimEnemyBgeComboBox {
            get {
                return ((string)(this["batchSimEnemyBgeComboBox"]));
            }
            set {
                this["batchSimEnemyBgeComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimCustomDecksComboBox {
            get {
                return ((string)(this["batchSimCustomDecksComboBox"]));
            }
            set {
                this["batchSimCustomDecksComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimGameModeComboBox {
            get {
                return ((string)(this["batchSimGameModeComboBox"]));
            }
            set {
                this["batchSimGameModeComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string guildSimOutputFormatComboBox {
            get {
                return ((string)(this["guildSimOutputFormatComboBox"]));
            }
            set {
                this["guildSimOutputFormatComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryPossibleCardsCheckBox1 {
            get {
                return ((string)(this["inventoryPossibleCardsCheckBox1"]));
            }
            set {
                this["inventoryPossibleCardsCheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryPossibleCardsCheckBox2 {
            get {
                return ((string)(this["inventoryPossibleCardsCheckBox2"]));
            }
            set {
                this["inventoryPossibleCardsCheckBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryPossibleCardsCheckBox3 {
            get {
                return ((string)(this["inventoryPossibleCardsCheckBox3"]));
            }
            set {
                this["inventoryPossibleCardsCheckBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimExtraFlagsTextBox {
            get {
                return ((string)(this["batchSimExtraFlagsTextBox"]));
            }
            set {
                this["batchSimExtraFlagsTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimDeckSizeLowTextBox {
            get {
                return ((string)(this["batchSimDeckSizeLowTextBox"]));
            }
            set {
                this["batchSimDeckSizeLowTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimDeckSizeHighTextBox {
            get {
                return ((string)(this["batchSimDeckSizeHighTextBox"]));
            }
            set {
                this["batchSimDeckSizeHighTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string queuedSimOutputFileTextBox {
            get {
                return ((string)(this["queuedSimOutputFileTextBox"]));
            }
            set {
                this["queuedSimOutputFileTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string queuedSimWriteToOneFileCheckBox {
            get {
                return ((string)(this["queuedSimWriteToOneFileCheckBox"]));
            }
            set {
                this["queuedSimWriteToOneFileCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimIterationsComboBox {
            get {
                return ((string)(this["batchSimIterationsComboBox"]));
            }
            set {
                this["batchSimIterationsComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimInventoryListBox {
            get {
                return ((string)(this["batchSimInventoryListBox"]));
            }
            set {
                this["batchSimInventoryListBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimSeedListBox {
            get {
                return ((string)(this["batchSimSeedListBox"]));
            }
            set {
                this["batchSimSeedListBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimShortcutSpeedComboBox {
            get {
                return ((string)(this["batchSimShortcutSpeedComboBox"]));
            }
            set {
                this["batchSimShortcutSpeedComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryFilterComboBox1 {
            get {
                return ((string)(this["inventoryFilterComboBox1"]));
            }
            set {
                this["inventoryFilterComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryFilterComboBox2 {
            get {
                return ((string)(this["inventoryFilterComboBox2"]));
            }
            set {
                this["inventoryFilterComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryFilterComboBox3 {
            get {
                return ((string)(this["inventoryFilterComboBox3"]));
            }
            set {
                this["inventoryFilterComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderUnfusedCheckbox {
            get {
                return ((string)(this["cardFinderUnfusedCheckbox"]));
            }
            set {
                this["cardFinderUnfusedCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderDualCheckbox {
            get {
                return ((string)(this["cardFinderDualCheckbox"]));
            }
            set {
                this["cardFinderDualCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderQuadCheckbox {
            get {
                return ((string)(this["cardFinderQuadCheckbox"]));
            }
            set {
                this["cardFinderQuadCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderEpicCheckbox {
            get {
                return ((string)(this["cardFinderEpicCheckbox"]));
            }
            set {
                this["cardFinderEpicCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderLegendCheckbox {
            get {
                return ((string)(this["cardFinderLegendCheckbox"]));
            }
            set {
                this["cardFinderLegendCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderVindCheckbox {
            get {
                return ((string)(this["cardFinderVindCheckbox"]));
            }
            set {
                this["cardFinderVindCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderImpCheckbox {
            get {
                return ((string)(this["cardFinderImpCheckbox"]));
            }
            set {
                this["cardFinderImpCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderRaiderCheckbox {
            get {
                return ((string)(this["cardFinderRaiderCheckbox"]));
            }
            set {
                this["cardFinderRaiderCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderBtCheckbox {
            get {
                return ((string)(this["cardFinderBtCheckbox"]));
            }
            set {
                this["cardFinderBtCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderXenoCheckbox {
            get {
                return ((string)(this["cardFinderXenoCheckbox"]));
            }
            set {
                this["cardFinderXenoCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderRtCheckbox {
            get {
                return ((string)(this["cardFinderRtCheckbox"]));
            }
            set {
                this["cardFinderRtCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderProgenCheckbox {
            get {
                return ((string)(this["cardFinderProgenCheckbox"]));
            }
            set {
                this["cardFinderProgenCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string cardFinderSection1to14Checkbox {
            get {
                return ((string)(this["cardFinderSection1to14Checkbox"]));
            }
            set {
                this["cardFinderSection1to14Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet2000Checkbox {
            get {
                return ((string)(this["cardFinderSet2000Checkbox"]));
            }
            set {
                this["cardFinderSet2000Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet2500Checkbox {
            get {
                return ((string)(this["cardFinderSet2500Checkbox"]));
            }
            set {
                this["cardFinderSet2500Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet6000Checkbox {
            get {
                return ((string)(this["cardFinderSet6000Checkbox"]));
            }
            set {
                this["cardFinderSet6000Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet9999Checkbox {
            get {
                return ((string)(this["cardFinderSet9999Checkbox"]));
            }
            set {
                this["cardFinderSet9999Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSetOtherCheckbox {
            get {
                return ((string)(this["cardFinderSetOtherCheckbox"]));
            }
            set {
                this["cardFinderSetOtherCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet7000Checkbox {
            get {
                return ((string)(this["cardFinderSet7000Checkbox"]));
            }
            set {
                this["cardFinderSet7000Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderAssaultCheckbox {
            get {
                return ((string)(this["cardFinderAssaultCheckbox"]));
            }
            set {
                this["cardFinderAssaultCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderStructureCheckbox {
            get {
                return ((string)(this["cardFinderStructureCheckbox"]));
            }
            set {
                this["cardFinderStructureCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderCommanderCheckbox {
            get {
                return ((string)(this["cardFinderCommanderCheckbox"]));
            }
            set {
                this["cardFinderCommanderCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderBoxCheckbox {
            get {
                return ((string)(this["cardFinderBoxCheckbox"]));
            }
            set {
                this["cardFinderBoxCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderChanceCheckbox {
            get {
                return ((string)(this["cardFinderChanceCheckbox"]));
            }
            set {
                this["cardFinderChanceCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderCacheCheckbox {
            get {
                return ((string)(this["cardFinderCacheCheckbox"]));
            }
            set {
                this["cardFinderCacheCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderPvPRewardCheckbox {
            get {
                return ((string)(this["cardFinderPvPRewardCheckbox"]));
            }
            set {
                this["cardFinderPvPRewardCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderPvERewardCheckbox {
            get {
                return ((string)(this["cardFinderPvERewardCheckbox"]));
            }
            set {
                this["cardFinderPvERewardCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string cardFinderPowerLowUpDown {
            get {
                return ((string)(this["cardFinderPowerLowUpDown"]));
            }
            set {
                this["cardFinderPowerLowUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string cardFinderFactionPowerLowUpDown {
            get {
                return ((string)(this["cardFinderFactionPowerLowUpDown"]));
            }
            set {
                this["cardFinderFactionPowerLowUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XMLOrder")]
        public string cardFinderSortByComboBox {
            get {
                return ((string)(this["cardFinderSortByComboBox"]));
            }
            set {
                this["cardFinderSortByComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderMythicCheckbox {
            get {
                return ((string)(this["cardFinderMythicCheckbox"]));
            }
            set {
                this["cardFinderMythicCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet8000Checkbox {
            get {
                return ((string)(this["cardFinderSet8000Checkbox"]));
            }
            set {
                this["cardFinderSet8000Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet8500Checkbox {
            get {
                return ((string)(this["cardFinderSet8500Checkbox"]));
            }
            set {
                this["cardFinderSet8500Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderDominionCheckbox {
            get {
                return ((string)(this["cardFinderDominionCheckbox"]));
            }
            set {
                this["cardFinderDominionCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderEventStructureCheckbox {
            get {
                return ((string)(this["cardFinderEventStructureCheckbox"]));
            }
            set {
                this["cardFinderEventStructureCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myDominionComboBox1 {
            get {
                return ((string)(this["myDominionComboBox1"]));
            }
            set {
                this["myDominionComboBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myDominionComboBox2 {
            get {
                return ((string)(this["myDominionComboBox2"]));
            }
            set {
                this["myDominionComboBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myDominionComboBox3 {
            get {
                return ((string)(this["myDominionComboBox3"]));
            }
            set {
                this["myDominionComboBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string cardFinderSection15Checkbox {
            get {
                return ((string)(this["cardFinderSection15Checkbox"]));
            }
            set {
                this["cardFinderSection15Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimMisTextBox {
            get {
                return ((string)(this["batchSimMisTextBox"]));
            }
            set {
                this["batchSimMisTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimFundTextBox {
            get {
                return ((string)(this["batchSimFundTextBox"]));
            }
            set {
                this["batchSimFundTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchSimGameHarmonicMeanCheckBox {
            get {
                return ((string)(this["batchSimGameHarmonicMeanCheckBox"]));
            }
            set {
                this["batchSimGameHarmonicMeanCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public string cardFinderPowerHighUpDown {
            get {
                return ((string)(this["cardFinderPowerHighUpDown"]));
            }
            set {
                this["cardFinderPowerHighUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public string cardFinderFactionPowerHighUpDown {
            get {
                return ((string)(this["cardFinderFactionPowerHighUpDown"]));
            }
            set {
                this["cardFinderFactionPowerHighUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cardFinderSkillTextBox {
            get {
                return ((string)(this["cardFinderSkillTextBox"]));
            }
            set {
                this["cardFinderSkillTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string cardFinderSection16Checkbox {
            get {
                return ((string)(this["cardFinderSection16Checkbox"]));
            }
            set {
                this["cardFinderSection16Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string minimizeToTray {
            get {
                return ((string)(this["minimizeToTray"]));
            }
            set {
                this["minimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navigatorPlayerDeckTextBox {
            get {
                return ((string)(this["navigatorPlayerDeckTextBox"]));
            }
            set {
                this["navigatorPlayerDeckTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navSimEnemyDeckTextBox {
            get {
                return ((string)(this["navSimEnemyDeckTextBox"]));
            }
            set {
                this["navSimEnemyDeckTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navSimBgeComboBox {
            get {
                return ((string)(this["navSimBgeComboBox"]));
            }
            set {
                this["navSimBgeComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navSimMyFortComboBox {
            get {
                return ((string)(this["navSimMyFortComboBox"]));
            }
            set {
                this["navSimMyFortComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navSimEnemyFortComboBox {
            get {
                return ((string)(this["navSimEnemyFortComboBox"]));
            }
            set {
                this["navSimEnemyFortComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navSimYourBgeComboBox {
            get {
                return ((string)(this["navSimYourBgeComboBox"]));
            }
            set {
                this["navSimYourBgeComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navSimEnemyBgeComboBox {
            get {
                return ((string)(this["navSimEnemyBgeComboBox"]));
            }
            set {
                this["navSimEnemyBgeComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string navSimCustomDecksComboBox {
            get {
                return ((string)(this["navSimCustomDecksComboBox"]));
            }
            set {
                this["navSimCustomDecksComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSet9500Checkbox {
            get {
                return ((string)(this["cardFinderSet9500Checkbox"]));
            }
            set {
                this["cardFinderSet9500Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string crowsNestSetDeckTextBox {
            get {
                return ((string)(this["crowsNestSetDeckTextBox"]));
            }
            set {
                this["crowsNestSetDeckTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSection17Checkbox {
            get {
                return ((string)(this["cardFinderSection17Checkbox"]));
            }
            set {
                this["cardFinderSection17Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSection18Checkbox {
            get {
                return ((string)(this["cardFinderSection18Checkbox"]));
            }
            set {
                this["cardFinderSection18Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string cardFinderSection19Checkbox {
            get {
                return ((string)(this["cardFinderSection19Checkbox"]));
            }
            set {
                this["cardFinderSection19Checkbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string firstCouncilSimCustomDecksComboBox {
            get {
                return ((string)(this["firstCouncilSimCustomDecksComboBox"]));
            }
            set {
                this["firstCouncilSimCustomDecksComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adminMiscCreateInventoryExtraFilteredCardsTextBox {
            get {
                return ((string)(this["adminMiscCreateInventoryExtraFilteredCardsTextBox"]));
            }
            set {
                this["adminMiscCreateInventoryExtraFilteredCardsTextBox"] = value;
            }
        }
    }
}
